# Generated by Django 4.0.5 on 2022-07-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='two_factor_key',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='two_factor_auth',
            field=models.CharField(blank=True, choices=[('Email', 'Email'), ('SMS', 'SMS'), ('Google Auth', 'Google Authenticator')], default=None, max_length=20, null=True),
        ),
    ]
