# Generated by Django 4.0.5 on 2022-07-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_two_factor_key_alter_account_two_factor_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='two_factor_key',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
