# Generated by Django 4.0.5 on 2022-07-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_account_two_factor_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='two_factor_key',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
