from django.shortcuts import render
from eye.models import Stock, Info, Financial


def stocks(request):
    return render(request, 'eye/stocks.html')

def calendar(request):
    return render(request, 'eye/calendar.html')

def education(request):
    return render(request, 'eye/education.html')

def screener(request):
    return render(request, 'eye/screener.html')

def portfolio(request):
    return render(request, 'eye/portfolio.html')


def symbol(request, symbol):
    symbol = Stock.objects.get(symbol=symbol)
    info = Info.objects.get(symbol=symbol)
    financial = Financial.objects.get(symbol=symbol)
    
    
    test = Financial.objects.filter(symbol=symbol, year=2020)[0].netIncome
    
    mode = "dark"
    
    data = {}
    
    stock = {
        'mode': mode,
        'test': test,
        'fin': financial,
        
        'symbol': symbol,
        'city': info.city,
        'state': info.state,
        'country': info.country,
        'address': info.address,
        'name': info.name,
        'summary': info.summary,
        'employees': info.employees,
        'sector': info.sector,
        'industry': info.industry,
        'exchange': info.exchange,
        'quoteType': info.quoteType,
        'currency': info.currency,
        'phone': info.phone,
        'website': info.website,
        'logo': info.logo,
        
        'fillingDate': financial.fillingDate,
        'period': financial.period,
        'revenue': financial.revenue,
        'costOfRevenue': financial.costOfRevenue,
        'grossProfit': financial.grossProfit,
        'grossProfitRatio': financial.grossProfitRatio,
        'researchAndDevelopmentExpenses': financial.researchAndDevelopmentExpenses,
        'generalAndAdministrativeExpenses': financial.generalAndAdministrativeExpenses,
        'sellingAndMarketingExpenses': financial.sellingAndMarketingExpenses,
        'sellingGeneralAndAdministrativeExpenses': financial.sellingGeneralAndAdministrativeExpenses,
        'otherExpenses': financial.otherExpenses,
        'operatingExpenses': financial.operatingExpenses,
        'costAndExpenses': financial.costAndExpenses,
        'interestIncome': financial.interestIncome,
        'interestExpense': financial.interestExpense,
        'depreciationAndAmortization': financial.depreciationAndAmortization,
        'ebitda': financial.ebitda,
        'ebitdaratio': financial.ebitdaratio,
        'operatingIncome': financial.operatingIncome,
        'operatingIncomeRatio': financial.operatingIncomeRatio,
        'totalOtherIncomeExpensesNet': financial.totalOtherIncomeExpensesNet,
        'incomeBeforeTax': financial.incomeBeforeTax,
        'incomeBeforeTaxRatio': financial.incomeBeforeTaxRatio,
        'incomeTaxExpense': financial.incomeTaxExpense,
        'netIncome': financial.netIncome,
        'netIncomeRatio': financial.netIncomeRatio,
        'eps': financial.eps,
        'epsdiluted': financial.epsdiluted,
        'weightedAverageShsOut': financial.weightedAverageShsOut,
        'weightedAverageShsOutDil': financial.weightedAverageShsOutDil,
        'link': financial.link,
        'finalLink': financial.finalLink,
        'cashAndCashEquivalents': financial.cashAndCashEquivalents,
        'shortTermInvestments': financial.shortTermInvestments,
        'cashAndShortTermInvestments': financial.cashAndShortTermInvestments,
        'netReceivables': financial.netReceivables,
        'inventory': financial.inventory,
        'otherCurrentAssets': financial.otherCurrentAssets,
        'totalCurrentAssets': financial.totalCurrentAssets,
        'propertyPlantEquipmentNet': financial.propertyPlantEquipmentNet,
        'goodwill': financial.goodwill,
        'intangibleAssets': financial.intangibleAssets,
        'goodwillAndIntangibleAssets': financial.goodwillAndIntangibleAssets,
        'longTermInvestments': financial.longTermInvestments,
        'taxAssets': financial.taxAssets,
        'otherNonCurrentAssets': financial.otherNonCurrentAssets,
        'totalNonCurrentAssets': financial.totalNonCurrentAssets,
        'otherAssets': financial.otherAssets,
        'totalAssets': financial.totalAssets,
        'accountPayables': financial.accountPayables,
        'shortTermDebt': financial.shortTermDebt,
        'taxPayables': financial.taxPayables,
        'deferredRevenue': financial.deferredRevenue,
        'otherCurrentLiabilities': financial.otherCurrentLiabilities,
        'totalCurrentLiabilities': financial.totalCurrentLiabilities,
        'longTermDebt': financial.longTermDebt,
        'deferredRevenueNonCurrent': financial.deferredRevenueNonCurrent,
        'deferredTaxLiabilitiesNonCurrent': financial.deferredTaxLiabilitiesNonCurrent,
        'otherNonCurrentLiabilities': financial.otherNonCurrentLiabilities,
        'totalNonCurrentLiabilities': financial.totalNonCurrentLiabilities,
        'otherLiabilities': financial.otherLiabilities,
        'capitalLeaseObligations': financial.capitalLeaseObligations,
        'totalLiabilities': financial.totalLiabilities,
        'preferredStock': financial.preferredStock,
        'commonStock': financial.commonStock,
        'retainedEarnings': financial.retainedEarnings,
        'accumulatedOtherComprehensiveIncomeLoss': financial.accumulatedOtherComprehensiveIncomeLoss,
        'othertotalStockholdersEquity': financial.othertotalStockholdersEquity,
        'totalStockholdersEquity': financial.totalStockholdersEquity,
        'totalLiabilitiesAndStockholdersEquity': financial.totalLiabilitiesAndStockholdersEquity,
        'minorityInterest': financial.minorityInterest,
        'totalEquity': financial.totalEquity,
        'totalLiabilitiesAndTotalEquity': financial.totalLiabilitiesAndTotalEquity,
        'totalInvestments': financial.totalInvestments,
        'totalDebt': financial.totalDebt,
        'netDebt': financial.netDebt,
        'deferredIncomeTax': financial.deferredIncomeTax,
        'stockBasedCompensation': financial.stockBasedCompensation,
        'changeInWorkingCapital': financial.changeInWorkingCapital,
        'accountsReceivables': financial.accountsReceivables,
        'accountsPayables': financial.accountsPayables,
        'otherWorkingCapital': financial.otherWorkingCapital,
        'otherNonCashItems': financial.otherNonCashItems,
        'netCashProvidedByOperatingActivities': financial.netCashProvidedByOperatingActivities,
        'investmentsInPropertyPlantAndEquipment': financial.investmentsInPropertyPlantAndEquipment,
        'acquisitionsNet': financial.acquisitionsNet,
        'purchasesOfInvestments': financial.purchasesOfInvestments,
        'salesMaturitiesOfInvestments': financial.salesMaturitiesOfInvestments,
        'otherInvestingActivites': financial.otherInvestingActivites,
        'netCashUsedForInvestingActivites': financial.netCashUsedForInvestingActivites,
        'debtRepayment': financial.debtRepayment,
        'commonStockIssued': financial.commonStockIssued,
        'commonStockRepurchased': financial.commonStockRepurchased,
        'dividendsPaid': financial.dividendsPaid,
        'otherFinancingActivites': financial.otherFinancingActivites,
        'netCashUsedProvidedByFinancingActivities': financial.netCashUsedProvidedByFinancingActivities,
        'effectOfForexChangesOnCash': financial.effectOfForexChangesOnCash,
        'netChangeInCash': financial.netChangeInCash,
        'cashAtEndOfPeriod': financial.cashAtEndOfPeriod,
        'cashAtBeginningOfPeriod': financial.cashAtBeginningOfPeriod,
        'operatingCashFlow': financial.operatingCashFlow,
        'capitalExpenditure': financial.capitalExpenditure,
        'freeCashFlow': financial.freeCashFlow,
        'revenuePerShare': financial.revenuePerShare,
        'netIncomePerShare': financial.netIncomePerShare,
        'operatingCashFlowPerShare': financial.operatingCashFlowPerShare,
        'freeCashFlowPerShare': financial.freeCashFlowPerShare,
        'cashPerShare': financial.cashPerShare,
        'bookValuePerShare': financial.bookValuePerShare,
        'tangibleBookValuePerShare': financial.tangibleBookValuePerShare,
        'shareholdersEquityPerShare': financial.shareholdersEquityPerShare,
        'interestDebtPerShare': financial.interestDebtPerShare,
        'marketCap': financial.marketCap,
        'enterpriseValue': financial.enterpriseValue,
        'peRatio': financial.peRatio,
        'priceToSalesRatio': financial.priceToSalesRatio,
        'pocfratio': financial.pocfratio,
        'pfcfRatio': financial.pfcfRatio,
        'pbRatio': financial.pbRatio,
        'ptbRatio': financial.ptbRatio,
        'evToSales': financial.evToSales,
        'enterpriseValueOverEBITDA': financial.enterpriseValueOverEBITDA,
        'evToOperatingCashFlow': financial.evToOperatingCashFlow,
        'evToFreeCashFlow': financial.evToFreeCashFlow,
        'earningsYield': financial.earningsYield,
        'freeCashFlowYield': financial.freeCashFlowYield,
        'debtToEquity': financial.debtToEquity,
        'debtToAssets': financial.debtToAssets,
        'netDebtToEBITDA': financial.netDebtToEBITDA,
        'currentRatio': financial.currentRatio,
        'interestCoverage': financial.interestCoverage,
        'incomeQuality': financial.incomeQuality,
        'dividendYield': financial.dividendYield,
        'payoutRatio': financial.payoutRatio,
        'salesGeneralAndAdministrativeToRevenue': financial.salesGeneralAndAdministrativeToRevenue,
        'researchAndDdevelopementToRevenue': financial.researchAndDdevelopementToRevenue,
        'intangiblesToTotalAssets': financial.intangiblesToTotalAssets,
        'capexToOperatingCashFlow': financial.capexToOperatingCashFlow,
        'capexToRevenue': financial.capexToRevenue,
        'capexToDepreciation': financial.capexToDepreciation,
        'stockBasedCompensationToRevenue': financial.stockBasedCompensationToRevenue,
        'grahamNumber': financial.grahamNumber,
        'roic': financial.roic,
        'returnOnTangibleAssets': financial.returnOnTangibleAssets,
        'grahamNetNet': financial.grahamNetNet,
        'workingCapital': financial.workingCapital,
        'tangibleAssetValue': financial.tangibleAssetValue,
        'netCurrentAssetValue': financial.netCurrentAssetValue,
        'investedCapital': financial.investedCapital,
        'averageReceivables': financial.averageReceivables,
        'averagePayables': financial.averagePayables,
        'averageInventory': financial.averageInventory,
        'daysSalesOutstanding': financial.daysSalesOutstanding,
        'daysPayablesOutstanding': financial.daysPayablesOutstanding,
        'daysOfInventoryOnHand': financial.daysOfInventoryOnHand,
        'receivablesTurnover': financial.receivablesTurnover,
        'payablesTurnover': financial.payablesTurnover,
        'inventoryTurnover': financial.inventoryTurnover,
        'roe': financial.roe,
        'capexPerShare': financial.capexPerShare,
        'quickRatio': financial.quickRatio,
        'cashRatio': financial.cashRatio,
        'daysOfSalesOutstanding': financial.daysOfSalesOutstanding,
        'daysOfInventoryOutstanding': financial.daysOfInventoryOutstanding,
        'operatingCycle': financial.operatingCycle,
        'daysOfPayablesOutstanding': financial.daysOfPayablesOutstanding,
        'cashConversionCycle': financial.cashConversionCycle,
        'grossProfitMargin': financial.grossProfitMargin,
        'operatingProfitMargin': financial.operatingProfitMargin,
        'pretaxProfitMargin': financial.pretaxProfitMargin,
        'netProfitMargin': financial.netProfitMargin,
        'effectiveTaxRate': financial.effectiveTaxRate,
        'returnOnAssets': financial.returnOnAssets,
        'returnOnEquity': financial.returnOnEquity,
        'returnOnCapitalEmployed': financial.returnOnCapitalEmployed,
        'netIncomePerEBT': financial.netIncomePerEBT,
        'ebtPerEbit': financial.ebtPerEbit,
        'ebitPerRevenue': financial.ebitPerRevenue,
        'debtRatio': financial.debtRatio,
        'debtEquityRatio': financial.debtEquityRatio,
        'longTermDebtToCapitalization': financial.longTermDebtToCapitalization,
        'totalDebtToCapitalization': financial.totalDebtToCapitalization,
        'cashFlowToDebtRatio': financial.cashFlowToDebtRatio,
        'companyEquityMultiplier': financial.companyEquityMultiplier,
        'fixedAssetTurnover': financial.fixedAssetTurnover,
        'assetTurnover': financial.assetTurnover,
        'operatingCashFlowSalesRatio': financial.operatingCashFlowSalesRatio,
        'freeCashFlowOperatingCashFlowRatio': financial.freeCashFlowOperatingCashFlowRatio,
        'cashFlowCoverageRatios': financial.cashFlowCoverageRatios,
        'shortTermCoverageRatios': financial.shortTermCoverageRatios,
        'capitalExpenditureCoverageRatio': financial.capitalExpenditureCoverageRatio,
        'dividendPaidAndCapexCoverageRatio': financial.dividendPaidAndCapexCoverageRatio,
        'dividendPayoutRatio': financial.dividendPayoutRatio,
        'priceBookValueRatio': financial.priceBookValueRatio,
        'priceToBookRatio': financial.priceToBookRatio,
        'priceEarningsRatio': financial.priceEarningsRatio,
        'priceToFreeCashFlowsRatio': financial.priceToFreeCashFlowsRatio,
        'priceToOperatingCashFlowsRatio': financial.priceToOperatingCashFlowsRatio,
        'priceCashFlowRatio': financial.priceCashFlowRatio,
        'priceEarningsToGrowthRatio': financial.priceEarningsToGrowthRatio,
        'priceSalesRatio': financial.priceSalesRatio,
        'enterpriseValueMultiple': financial.enterpriseValueMultiple,
        'priceFairValue': financial.priceFairValue,
        'revenueGrowth': financial.revenueGrowth,
        'grossProfitGrowth': financial.grossProfitGrowth,
        'ebitgrowth': financial.ebitgrowth,
        'operatingIncomeGrowth': financial.operatingIncomeGrowth,
        'netIncomeGrowth': financial.netIncomeGrowth,
        'epsgrowth': financial.epsgrowth,
        'epsdilutedGrowth': financial.epsdilutedGrowth,
        'weightedAverageSharesGrowth': financial.weightedAverageSharesGrowth,
        'weightedAverageSharesDilutedGrowth': financial.weightedAverageSharesDilutedGrowth,
        'dividendsperShareGrowth': financial.dividendsperShareGrowth,
        'operatingCashFlowGrowth': financial.operatingCashFlowGrowth,
        'freeCashFlowGrowth': financial.freeCashFlowGrowth,
        'tenYRevenueGrowthPerShare': financial.tenYRevenueGrowthPerShare,
        'fiveYRevenueGrowthPerShare': financial.fiveYRevenueGrowthPerShare,
        'threeYRevenueGrowthPerShare': financial.threeYRevenueGrowthPerShare,
        'tenYOperatingCFGrowthPerShare': financial.tenYOperatingCFGrowthPerShare,
        'fiveYOperatingCFGrowthPerShare': financial.fiveYOperatingCFGrowthPerShare,
        'threeYOperatingCFGrowthPerShare': financial.threeYOperatingCFGrowthPerShare,
        'tenYNetIncomeGrowthPerShare': financial.tenYNetIncomeGrowthPerShare,
        'fiveYNetIncomeGrowthPerShare': financial.fiveYNetIncomeGrowthPerShare,
        'threeYNetIncomeGrowthPerShare': financial.threeYNetIncomeGrowthPerShare,
        'tenYShareholdersEquityGrowthPerShare': financial.tenYShareholdersEquityGrowthPerShare,
        'fiveYShareholdersEquityGrowthPerShare': financial.fiveYShareholdersEquityGrowthPerShare,
        'threeYShareholdersEquityGrowthPerShare': financial.threeYShareholdersEquityGrowthPerShare,
        'tenYDividendperShareGrowthPerShare': financial.tenYDividendperShareGrowthPerShare,
        'fiveYDividendperShareGrowthPerShare': financial.fiveYDividendperShareGrowthPerShare,
        'threeYDividendperShareGrowthPerShare': financial.threeYDividendperShareGrowthPerShare,
        'receivablesGrowth': financial.receivablesGrowth,
        'inventoryGrowth': financial.inventoryGrowth,
        'assetGrowth': financial.assetGrowth,
        'bookValueperShareGrowth': financial.bookValueperShareGrowth,
        'debtGrowth': financial.debtGrowth,
        'rdexpenseGrowth': financial.rdexpenseGrowth,
        'sgaexpensesGrowth': financial.sgaexpensesGrowth,
        'date': financial.date,
        'stockPrice': financial.stockPrice,
        'DCF': financial.DCF,
        
    }
    return render(request, 'eye/symbol.html', stock)