# Generated by Django 4.0.4 on 2022-05-26 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('summary', models.CharField(max_length=10000)),
                ('employees', models.IntegerField()),
                ('sector', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=200)),
                ('exchange', models.CharField(max_length=50)),
                ('quoteType', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=300)),
                ('logo', models.CharField(max_length=500)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eye.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Cashflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('netIncome', models.IntegerField(blank=True, default=0, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eye.stock')),
            ],
        ),
    ]
