# Generated by Django 4.0.4 on 2022-06-09 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='address',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='cik',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='city',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='country',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='finalLink',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='link',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='period',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quoteType',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='state',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='website',
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('ticker', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('summary', models.CharField(blank=True, max_length=10000, null=True)),
                ('employees', models.FloatField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=200, null=True)),
                ('industry', models.CharField(blank=True, max_length=200, null=True)),
                ('exchange', models.CharField(blank=True, max_length=50, null=True)),
                ('quoteType', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, max_length=300, null=True)),
                ('logo', models.URLField(blank=True, max_length=500, null=True)),
                ('period', models.CharField(blank=True, max_length=5, null=True)),
                ('cik', models.IntegerField(blank=True, null=True)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('finalLink', models.URLField(blank=True, max_length=500, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eye.stock')),
            ],
        ),
    ]
