# Generated by Django 4.0.6 on 2022-08-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='ticker',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
