# Generated by Django 4.0.4 on 2022-05-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='netIncome',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
