# Generated by Django 4.0.6 on 2022-08-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0002_history_date_history_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
