# Generated by Django 4.0.4 on 2022-06-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0002_alter_info_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='state',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
    ]
