# Generated by Django 4.0.4 on 2022-06-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0003_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='user',
            new_name='host',
        ),
    ]
