# Generated by Django 4.0.4 on 2022-05-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0004_financials_delete_cashflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='financials',
            name='depreciationAndAmortization',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financials',
            name='ebitda',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financials',
            name='ebitdaratio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financials',
            name='eps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financials',
            name='epsdiluted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financials',
            name='fillingDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financials',
            name='finalLink',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='financials',
            name='incomeBeforeTax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financials',
            name='incomeBeforeTaxRatio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financials',
            name='incomeTaxExpense',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financials',
            name='interestExpense',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financials',
            name='interestIncome',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financials',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='financials',
            name='netIncomeRatio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financials',
            name='operatingIncome',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financials',
            name='operatingIncomeRatio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financials',
            name='totalOtherIncomeExpensesNet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financials',
            name='weightedAverageShsOut',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financials',
            name='weightedAverageShsOutDil',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
