# Generated by Django 4.0.4 on 2022-06-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0005_alter_portfolio_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='stocks',
            field=models.ManyToManyField(blank=True, related_name='stocks', to='eye.stock'),
        ),
    ]
