# Generated by Django 4.0.4 on 2022-05-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0006_rename_financials_financial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financial',
            name='id',
        ),
        migrations.AddField(
            model_name='financial',
            name='year',
            field=models.IntegerField(default=2022, primary_key=True, serialize=False),
        ),
    ]
