# Generated by Django 4.0.4 on 2022-06-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0006_portfolio_stocks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='portf_name',
            new_name='name',
        ),
    ]
