# Generated by Django 4.0.4 on 2022-05-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0007_remove_financial_id_financial_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial',
            name='accountPayables',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='accumulatedOtherComprehensiveIncomeLoss',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='capitalLeaseObligations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='cashAndCashEquivalents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='cashAndShortTermInvestments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='commonStock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='deferredRevenue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='deferredRevenueNonCurrent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='deferredTaxLiabilitiesNonCurrent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='goodwill',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='goodwillAndIntangibleAssets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='intangibleAssets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='inventory',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='longTermDebt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='longTermInvestments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='minorityInterest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='netDebt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='netReceivables',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='otherAssets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='otherCurrentAssets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='otherCurrentLiabilities',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='otherLiabilities',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='otherNonCurrentAssets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='otherNonCurrentLiabilities',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='othertotalStockholdersEquity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='period',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='preferredStock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='propertyPlantEquipmentNet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='retainedEarnings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='shortTermDebt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='shortTermInvestments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='taxAssets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='taxPayables',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='totalAssets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='totalCurrentAssets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='totalCurrentLiabilities',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='totalDebt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='totalEquity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='totalInvestments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='totalLiabilities',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='totalLiabilitiesAndStockholdersEquity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='totalLiabilitiesAndTotalEquity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='totalNonCurrentAssets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='totalNonCurrentLiabilities',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='totalStockholdersEquity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
