# Generated by Django 4.0.4 on 2022-06-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0007_rename_portf_name_portfolio_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='financial',
            index=models.Index(fields=['year'], name='eye_financi_year_cf6af2_idx'),
        ),
    ]
