# Generated by Django 4.0.4 on 2022-05-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0008_financial_accountpayables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial',
            name='DCF',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='accountsPayables',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='accountsReceivables',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='acquisitionsNet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='assetGrowth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='assetTurnover',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='averageInventory',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='averagePayables',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='averageReceivables',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='bookValuePerShare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='bookValueperShareGrowth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='capexPerShare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='capexToDepreciation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='capexToOperatingCashFlow',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='capexToRevenue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='capitalExpenditure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='capitalExpenditureCoverageRatio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='cashAtBeginningOfPeriod',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='cashAtEndOfPeriod',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='cashConversionCycle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='cashFlowCoverageRatios',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='cashFlowToDebtRatio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='cashPerShare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='cashRatio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='changeInWorkingCapital',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='commonStockIssued',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='commonStockRepurchased',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='companyEquityMultiplier',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='currentRatio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='daysOfInventoryOnHand',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='daysOfInventoryOutstanding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='daysOfPayablesOutstanding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='daysOfSalesOutstanding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='daysPayablesOutstanding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='daysSalesOutstanding',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='debtEquityRatio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='debtGrowth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='debtRatio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='debtRepayment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='debtToAssets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='debtToEquity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='deferredIncomeTax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='dividendPaidAndCapexCoverageRatio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='dividendPayoutRatio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='dividendYield',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='dividendsPaid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='dividendsperShareGrowth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='earningsYield',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='ebitPerRevenue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='ebitgrowth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='ebtPerEbit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='effectOfForexChangesOnCash',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='effectiveTaxRate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='enterpriseValue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='enterpriseValueMultiple',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='enterpriseValueOverEBITDA',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='epsdilutedGrowth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='epsgrowth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='evToFreeCashFlow',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='evToOperatingCashFlow',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='evToSales',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='fiveYDividendperShareGrowthPerShare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='fiveYNetIncomeGrowthPerShare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='fiveYOperatingCFGrowthPerShare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='fiveYRevenueGrowthPerShare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='fiveYShareholdersEquityGrowthPerShare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='fixedAssetTurnover',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='freeCashFlow',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='freeCashFlowGrowth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='freeCashFlowOperatingCashFlowRatio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='freeCashFlowPerShare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='freeCashFlowYield',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='grahamNetNet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='grahamNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='grossProfitGrowth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='grossProfitMargin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='incomeQuality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='intangiblesToTotalAssets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='interestCoverage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='interestDebtPerShare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='inventoryGrowth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='inventoryTurnover',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='investedCapital',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='investmentsInPropertyPlantAndEquipment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='longTermDebtToCapitalization',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='marketCap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='netCashProvidedByOperatingActivities',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='netCashUsedForInvestingActivites',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='netCashUsedProvidedByFinancingActivities',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='netChangeInCash',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='netCurrentAssetValue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='netDebtToEBITDA',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='netIncomeGrowth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='netIncomePerEBT',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='netIncomePerShare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='netProfitMargin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='operatingCashFlow',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='operatingCashFlowGrowth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='operatingCashFlowPerShare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='operatingCashFlowSalesRatio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='operatingCycle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='operatingIncomeGrowth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='operatingProfitMargin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='otherFinancingActivites',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='otherInvestingActivites',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='otherNonCashItems',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='otherWorkingCapital',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='payablesTurnover',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='payoutRatio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='pbRatio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='peRatio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='pfcfRatio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='pocfratio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='pretaxProfitMargin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='priceBookValueRatio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='priceCashFlowRatio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='priceEarningsRatio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='priceEarningsToGrowthRatio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='priceFairValue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='priceSalesRatio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='priceToBookRatio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='priceToFreeCashFlowsRatio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='priceToOperatingCashFlowsRatio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='priceToSalesRatio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='ptbRatio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='purchasesOfInvestments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='quickRatio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='rdexpenseGrowth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='receivablesGrowth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='receivablesTurnover',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='researchAndDdevelopementToRevenue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='returnOnAssets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='returnOnCapitalEmployed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='returnOnEquity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='returnOnTangibleAssets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='revenueGrowth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='revenuePerShare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='roe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='roic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='salesGeneralAndAdministrativeToRevenue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='salesMaturitiesOfInvestments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='sgaexpensesGrowth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='shareholdersEquityPerShare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='shortTermCoverageRatios',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='stockBasedCompensation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='stockBasedCompensationToRevenue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='stockPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='tangibleAssetValue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='tangibleBookValuePerShare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='tenYDividendperShareGrowthPerShare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='tenYNetIncomeGrowthPerShare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='tenYOperatingCFGrowthPerShare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='tenYRevenueGrowthPerShare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='tenYShareholdersEquityGrowthPerShare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='threeYDividendperShareGrowthPerShare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='threeYNetIncomeGrowthPerShare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='threeYOperatingCFGrowthPerShare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='threeYRevenueGrowthPerShare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='threeYShareholdersEquityGrowthPerShare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='totalDebtToCapitalization',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='weightedAverageSharesDilutedGrowth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='weightedAverageSharesGrowth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financial',
            name='workingCapital',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
