# Generated by Django 4.0.4 on 2022-05-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0009_financial_dcf_financial_accountspayables_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial',
            name='assetGrowth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='assetTurnover',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='averageInventory',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='averagePayables',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='averageReceivables',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='bookValuePerShare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='bookValueperShareGrowth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='capexPerShare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='capexToDepreciation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='capexToOperatingCashFlow',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='capexToRevenue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='capitalExpenditureCoverageRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='cashConversionCycle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='cashFlowCoverageRatios',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='cashFlowToDebtRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='cashPerShare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='cashRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='companyEquityMultiplier',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='currentRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='daysOfInventoryOnHand',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='daysOfInventoryOutstanding',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='daysOfPayablesOutstanding',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='daysOfSalesOutstanding',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='daysPayablesOutstanding',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='daysSalesOutstanding',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='debtEquityRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='debtGrowth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='debtRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='debtToAssets',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='debtToEquity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='dividendPaidAndCapexCoverageRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='dividendPayoutRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='dividendYield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='dividendsperShareGrowth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='earningsYield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='ebitPerRevenue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='ebitdaratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='ebitgrowth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='ebtPerEbit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='effectiveTaxRate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='enterpriseValue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='enterpriseValueMultiple',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='enterpriseValueOverEBITDA',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='eps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='epsdiluted',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='epsdilutedGrowth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='epsgrowth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='evToFreeCashFlow',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='evToOperatingCashFlow',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='evToSales',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='fiveYDividendperShareGrowthPerShare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='fiveYNetIncomeGrowthPerShare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='fiveYOperatingCFGrowthPerShare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='fiveYRevenueGrowthPerShare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='fiveYShareholdersEquityGrowthPerShare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='fixedAssetTurnover',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='freeCashFlowGrowth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='freeCashFlowOperatingCashFlowRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='freeCashFlowPerShare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='freeCashFlowYield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='grahamNetNet',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='grahamNumber',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='grossProfitGrowth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='grossProfitMargin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='grossProfitRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='incomeBeforeTaxRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='incomeQuality',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='intangiblesToTotalAssets',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='interestCoverage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='interestDebtPerShare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='inventoryGrowth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='inventoryTurnover',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='investedCapital',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='longTermDebtToCapitalization',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='marketCap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='netCurrentAssetValue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='netDebtToEBITDA',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='netIncomeGrowth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='netIncomePerEBT',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='netIncomePerShare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='netIncomeRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='netProfitMargin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='operatingCashFlowGrowth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='operatingCashFlowPerShare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='operatingCashFlowSalesRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='operatingCycle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='operatingIncomeGrowth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='operatingIncomeRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='operatingProfitMargin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='payablesTurnover',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='payoutRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='pbRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='peRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='pfcfRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='pocfratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='pretaxProfitMargin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='priceBookValueRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='priceCashFlowRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='priceEarningsRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='priceEarningsToGrowthRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='priceFairValue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='priceSalesRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='priceToBookRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='priceToFreeCashFlowsRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='priceToOperatingCashFlowsRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='priceToSalesRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='ptbRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='quickRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='rdexpenseGrowth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='receivablesGrowth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='receivablesTurnover',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='researchAndDdevelopementToRevenue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='returnOnAssets',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='returnOnCapitalEmployed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='returnOnEquity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='returnOnTangibleAssets',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='revenueGrowth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='revenuePerShare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='roe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='roic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='salesGeneralAndAdministrativeToRevenue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='sgaexpensesGrowth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='shareholdersEquityPerShare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='shortTermCoverageRatios',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='stockBasedCompensationToRevenue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='tangibleAssetValue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='tangibleBookValuePerShare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='tenYDividendperShareGrowthPerShare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='tenYNetIncomeGrowthPerShare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='tenYOperatingCFGrowthPerShare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='tenYRevenueGrowthPerShare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='tenYShareholdersEquityGrowthPerShare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='threeYDividendperShareGrowthPerShare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='threeYNetIncomeGrowthPerShare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='threeYOperatingCFGrowthPerShare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='threeYRevenueGrowthPerShare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='threeYShareholdersEquityGrowthPerShare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='totalDebtToCapitalization',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='weightedAverageSharesDilutedGrowth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='weightedAverageSharesGrowth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='workingCapital',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
