# Generated by Django 4.0.4 on 2022-06-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0010_remove_financial_eye_financi_symbol__9fa4f5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial',
            name='year',
            field=models.IntegerField(db_index=True),
        ),
    ]
