# Generated by Django 4.0.4 on 2022-06-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0010_alter_financial_assetgrowth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial',
            name='commonStock',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='preferredStock',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='ticker',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='financial',
            name='year',
            field=models.IntegerField(default=2021),
        ),
        migrations.AlterField(
            model_name='info',
            name='employees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
