# Generated by Django 4.0.4 on 2022-06-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0011_alter_financial_year'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='financial',
            name='eye_financi_symbol__6f2987_idx',
        ),
    ]
