# Generated by Django 4.0.4 on 2022-06-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0012_remove_financial_eye_financi_symbol__6f2987_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial',
            name='year',
            field=models.IntegerField(),
        ),
    ]
