# Generated by Django 4.0.4 on 2022-06-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0013_alter_financial_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial',
            name='year',
            field=models.IntegerField(db_index=True),
        ),
    ]
