# Generated by Django 4.0.4 on 2022-06-19 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0014_alter_financial_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='host',
            new_name='user',
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eye.stock')),
            ],
        ),
    ]
