# Generated by Django 4.0.4 on 2022-06-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0015_rename_host_portfolio_user_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='closePct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='closePrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='highPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='lowPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='openPrice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
