# Generated by Django 4.0.4 on 2022-06-22 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0016_history_closepct_history_closeprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortFinancial',
            fields=[
                ('year', models.IntegerField(db_index=True)),
                ('verification', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('revenue', models.FloatField(blank=True, null=True)),
                ('eps', models.FloatField(blank=True, null=True)),
                ('marketCap', models.FloatField(blank=True, null=True)),
                ('enterpriseValue', models.FloatField(blank=True, null=True)),
                ('peRatio', models.FloatField(blank=True, null=True)),
                ('priceToSalesRatio', models.FloatField(blank=True, null=True)),
                ('pfcfRatio', models.FloatField(blank=True, null=True)),
                ('pbRatio', models.FloatField(blank=True, null=True)),
                ('debtToEquity', models.FloatField(blank=True, null=True)),
                ('debtToAssets', models.FloatField(blank=True, null=True)),
                ('netDebtToEBITDA', models.FloatField(blank=True, null=True)),
                ('currentRatio', models.FloatField(blank=True, null=True)),
                ('dividendYield', models.FloatField(blank=True, null=True)),
                ('payoutRatio', models.FloatField(blank=True, null=True)),
                ('roic', models.FloatField(blank=True, null=True)),
                ('roe', models.FloatField(blank=True, null=True)),
                ('quickRatio', models.FloatField(blank=True, null=True)),
                ('cashRatio', models.FloatField(blank=True, null=True)),
                ('grossProfitMargin', models.FloatField(blank=True, null=True)),
                ('operatingProfitMargin', models.FloatField(blank=True, null=True)),
                ('pretaxProfitMargin', models.FloatField(blank=True, null=True)),
                ('netProfitMargin', models.FloatField(blank=True, null=True)),
                ('debtRatio', models.FloatField(blank=True, null=True)),
                ('assetTurnover', models.FloatField(blank=True, null=True)),
                ('revenueGrowth', models.FloatField(blank=True, null=True)),
                ('debtGrowth', models.FloatField(blank=True, null=True)),
                ('DCF', models.FloatField(blank=True, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eye.stock')),
            ],
        ),
    ]
