# Generated by Django 4.0.4 on 2022-06-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0020_alter_stock_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='marketCap',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
