# Generated by Django 4.0.4 on 2022-06-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0021_info_marketcap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='summary',
            new_name='description',
        ),
    ]
