# Generated by Django 4.0.5 on 2022-06-28 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0024_remove_financial_assetgrowth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='sharesOutstanding',
        ),
        migrations.RemoveField(
            model_name='shortfinancial',
            name='pretaxProfitMargin',
        ),
    ]
