# Generated by Django 4.0.5 on 2022-06-28 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0026_rename_forwardeps_info_forwardeps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='address',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='employees',
            new_name='fullTimeEmployees',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='logo',
            new_name='logo_url',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='description',
            new_name='longBusinessSummary',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='name',
            new_name='longName',
        ),
    ]
